asthet = feeling 感觉
esthet = feeling 感觉
abl = able 能力
abili = able 能力
acid = sour, sharp 尖，酸，锐，利
acri = sour, sharp 尖，酸，锐，利
acrid = sour, sharp 尖，酸，锐，利
acu = sour, sharp 尖，酸，锐，利
acro = top 顶点，高点
act = to do, to drive 行动，做
aer = air 空气，充气
aero = air 空气，充气
aeri = air 空气，充气
ag = do, act 做，代理做
agog = lead 引导
agon = struggle 挣扎，斗争
agri = field, land 田地，农业
agro = field, land 田地，农业
agr = field, land 田地，农业
alb = white 白色
alg = pain 痛
alt = high 高
alter = other, to change 其他的，改变状态
altern = other, to change 其他的，改变状态
ali = other, to change 其他的，改变状态
am = love 爱，情爱
amor = love 爱，情爱
amat = love 爱，情爱
ambul = walk 行走，走路
ampl = large 大
andro = male, man 男人
anim = life, spirit 生命，精神
anthrop = man, human 人，人类
aqu = water 水
arbit = judge 判断
arbir = judge 判断
arc = bow 弓
arh = bow 弓
arm = weapon 武器
art = skill, joint, trick 技巧，关节，诡计
anci, antiq = old 古老
ann, enn = year 年，一年
apt, ept = fit, ability 适应，能力
arch, archy = ruler, rule, chief 统治者，统治，主要的
astro, aster = star 星星
audi, audit = hear 听
aug = increase 增加
av, avar, avi = desire, bird 渴望，鸟
ball, bol = throw, dance, ball 抛，舞，球
balm = balsam 香油
ban = prohibit 禁止
bar = weight 重，压
barr = stick 棒，栏
bas, base = low, foundation 低下，基础
bat = beat 打，击
bell, bel = war, fight 战争，打斗
biblio = book 书
bio, bi = life 生命，生物
blanc = white 白
brace = two arms两臂
braid = twist 扭
brev, bridg = short 短，缩短
bu = ox 牛
cad, cas, cid = fall 落下，降临
calc = stone 石头
calori = heat 热
camp = field 田野
cand = white, glow 白，发光
cant, cent = sing, song 唱，歌
cap, capt, cept, ceive, cip, cup = take, hold, seize 拿，抓，握住
cap, cipit = head 头
car, char = dear 可爱的
card, chart = paper 纸片
card, cord = heart 心脏，一致
carn = flesh 肉，肉欲
cast = pure 纯洁
cav = hole 洞
ced, ceed, cess = go 行走，前进
celer = quick, speed 快，速
cens = judge 判断
cent = hundred 一百
centr = center 中心
cern, cert, cret = sure, separate 搞清，区别
chor = dance, sing 歌，舞
chrom = color 颜色
chron = time 时间
cid, cis = cut, kill 切开，杀
cil(i) = call 召集
circ, cycl = ring, circle 圆，环
cit = quote, call 引用，唤起
civ = citizen 公民
claim, clam = cry out, shout 呼喊，叫喊
clear, clar, clair = clear, bright 清楚，明白
clin, cliv = lean, slope 侵斜，斜坡
clos,clud, clus = close 关闭
coct = cook 煮，调配
cogn = know 知道
com = banquet 宴会
commod = convenient 方便
cond = hide 藏
corn = horn 角
corp, corpor = body 身体，团体
cosm(o) = world 世界，宇宙
cracy = rule 统治或政体
crat = ruler统治者
cre, creas = grow, make 增长，产生
creed, cred = believe, trust 相信，信任
crit, cris = judge, discern 判断，分辨
cruc, crus, crux = cross 十字形，交叉
cryo = cold 冷，冻
crypt = secret, hidden 秘密，隐藏
cub, cumb = lie down 躺
culp = fault 错，罪
cult = till 耕种，培养
cumber = barrier躺的东西，障碍
cur = care 关心
cur, curr, curs, cour, cours = run 跑，发生
cuss = shake 摇动
custom = habit 习惯
cyn = dog 狗
dem(o) = people 人民，人们
demn = harm 伤害
dens = make thick 变浓厚
dent = tooth 牙齿
derm, dermat = skin 皮肤
dexter = right 右边
di = day 日，日子
dict, dic = say, assert 说话，断言
dign = worthy, noble 值得，高贵
doc, doct = to teach 教
dole = grieve 悲伤
dom = house 屋，家
don, dit = give 给予
dorm = sleep 睡眠
dox = opinion 观点
draw = pull 拉
drom = run 跑
du, dub, doub = two 二，双
duc, duct = lead, bring 引导，带来
dur = last, hard 持久，坚硬
dyn, dynam = power 力量
ed = eat 吃
ego = I 我，自己
em, empt, ampl = take, procure 拿，获得
emper, imper = command 命令，统治
equ, equi = equal, even 相等，平均
erg, ert = energy, work 能量，活动
err = wander, mistake 漫游，犯错误
ev = age 年龄，时代
extr(e), exter = out 出去
fabl, fabul = speak 讲，说
fabric = make 制作
fac, fact, fect, fic, fig = make, do 做，制作
fac, fic = face 脸，面
fall, fail, fault = err, deceive 犯错误，欺骗
feder = league 联盟
fend, fens = strike 打击
fer = bring, carry 带来，拿来
ferv = boil 沸，热
fess = speak 说
fest = feast 节日
fest = hostile 仇恨
fid = trust, faith 相信，信念
fil, fili = thread 线条
fin = end, boundary 结束，范围
firm = firm 坚定
fix = fix 固定
flam, flagr = blaze 火焰
flat = blow 吹
flect, flex = bend 弯曲
flict = strike 打击
flor, flour = flower 花
flu = flow 流动
foli = leaf 树叶
forc, fort = strong 强大，力量
form = shape 形状
fortu = luck 运气
found, fund = base基础
fract, frag = break 打碎
frig, friger = cold 冷
front = forehead 前额
fug = flee 逃，离开
fum = smoke烟
funct = perform活动
fus = pour 流，泻
gam, gamy = marriage婚姻
gar, garn = furnish装饰，供应
gen, gener, genit = birth, produce 出生，产生
geo = earth 地，地球
germ = seed种子
gest, gister = carry, bring 带来，产生
glaci = ice冰
gloss, glot = tongue舌头，词语
gnos(t), gnor = know 知道
gon = angle 角
grad = step, grade 步，级
gran = grain颗粒
graph, gram = write 写，图
grat, gree = pleasing 感激，高兴
grav, griev = heavy重
greg = group群体
gress = go, walk行走
gyn, gynec = woman妇女
habit = dwell居住
hal = breathe呼吸
hap = chance机会，运气
haust = draw water抽水
hav = possess拥有
head = head头
heli(o) = sun太阳
helic = spiral螺旋
her, hes = stick粘附
hibit = hold拿住
hilar = glad高兴
hor(r) = shudder, dread颤抖，害怕
hort = encourage鼓励
hospit, host = guest客人
hum = earth土，地
hydr, hydro = water水
hypn(o) = sleep睡眠
idea, ideo = idea思想，观点
idio = peculiar, private特殊的，个人的
idol = image形象，偶像
imag, imit = imagine, likeness想象，相象
insul = island岛屿
integr = whole完整
it = go行走
ject = throw, cast投掷，扔
joc = joke消化
journ = day日期
judg, judic = judge判断
jug = yoke牛轭
junct, join = join结合，连接
jur, juris = swear, law发誓，法律
juven = young年轻
labor = labor劳动
lact = milk奶，乳
langu = faint虚弱
lapid = stone石头
laps = slip滑，滑走
lat = bring out拿出，带出
later = side边
lav, luv, lut = wash洗，冲洗
lax = loose松
lect, leg = speak, read讲，读
lect, lig = choose, gather选择，收集
leg, legis = law法律
lev, liev = raise, lighten举起，变轻
lex, lexic = word, speech词汇
liber = free自由
libr = book书
lic = allure引诱
licen = allow允许
limin, lim = threshold门槛，限制
line = line直线，线条
lingu = language语言，原意为舌头
linqu = leave离开
lips = leave离开
liqu = wet湿
liter = letter文字，字母
lith = stone石头
loc = place地方
log, logu = speak说话
logy, ology = science科学，学科
long = long长
loqu,locu = speak说话
luc, lust = light, shine光，照亮
lud, lus = play玩，戏剧
lumin = light光
lun = moon月亮
lustr = light光亮
lys, lysis = break down裂开，分假
mach, mech = machine机器
magn = big大
maj = great大，伟大
man, main = stay逗留
man, manu = hand手
mand = order命令
mari = sea海洋
mark = sign记号，符号
matern, matr = mother母性，母亲
med, medi = middle中间
memor = memory记忆
mend = free from fault改错
ment = mind思考，神志
merc, merch = trade交易
merg, mers = sink沉，没
meter, metr, meas, mens = measure计量，测量
migr = remove迁移
milit = soldier兵
min = project伸出，突出
mini, min = small小
mir = wonder, look惊奇，看
mis(o) = hate恨
misc = mix混淆
miser = wretched可怜的
miss, mit = send, cast送，放出
mnes, mnem = remember记忆
mob = move动
mod = mode, manner方式，模式，风度
moll = soft软
mon, monit = warn警告
monstr = show显示
mor = moral道德
mord, mors = bite咬
morph = form, shape形状
mort = death死
mot = move运动
mount = ascend登上
muni, mum = public公共的
mur = wall墙壁
mus = muse娱乐
mut = change改变
nat = born出生
nav, naus, naut = ship船，海员
nect, nex = bind连接
neg = deny否认
negr, nigr = black黑
neur = nerve神经
nihil = nothing无，不存在
noc, nox = hurt, poison伤害，毒
noct = night夜晚
nom(y) = a field of knowledge某一领域的知识
nomin = name名称，名字
norm = rule, norm规则，规范
nost = home家
not = know知道
nounce, nunci = speak讲话，说出
nov = new新的
null = none没有
numer = number数目
nutrit, nutri = nourish营养
od = song歌曲
oner = load负担
onym = name名字
oper = work工作
opt = choose选择
opt, opto = sight视力
optim = best最好
ora, orat = mouth嘴，说
orbit = circle圆圈
ordin = order命令，顺序
ori, orig = rise, begin升起，开始
orn = embellish装饰
oss = bone骨头
ot(o) = ear耳朵
pact = fastened紧的
palp = feel感觉，摸
par = bring forth生产，生出孩子
par = equal平等
par = get ready准备
par, pear = come in sight看见
parl = speak说话
part, port = part, divide部分，分开
pass = feeling感情
pass = pass through通过
path = feeling, suffering, illness感情，痛苦，病
patr(i) = father父亲
ped = child, education儿童，教育
ped = foot脚
pel, puls = drive, push驱动，推
pen, pun = penalty惩罚
pend, pens = hang悬挂
pend, pens, pond = weight, expend称重量，称银子，花费
peri = try尝试
pet = seek追求，寻求
petr(o) = stone石头
phag = eat吃
phan = show出示
phil, philo = love爱
phob, phobia = dislike厌恶
phon = sound声音
phor = bring带来
photo = light光
phyt(o) = plant植物
pict = paint描画
pisc = fish鱼
plac = calm平静
place = place放，地方
plaint = complain抱怨
plannt = plant种植
plat = flat平坦
plaud = clap hands鼓掌
ple, plen, plet, pli = full, fill满，填满
plex = fold重叠
plic, ply = fold重叠
plod = big noise大声音
plor = cry, weep喊，哭
ploy = use, involve用，参与
plumb = lead铅
point, punct = point, make sharp点，变尖
polic, polis, polit = state, city国家，城市
pon, pound = put放置
popul, publ = people人民
porc = pig猪
port = carry拿，运
pos, posit = put放
post, poster = behind后面
pot = drink喝
poten = powerful有力的
prais, preci = value价值
prehens, prehend = catch抓住
press = press挤压
prim = first, chief第一，主要的
pris = take拿住，抓住
priv = single, alone单个
proach = near接近
prob, prov = test测试，证明
prol = offspring后代，子孙
proper, propri = one’s own拥有，恰当的
proxim = close, near接近，靠近
pud, pudi = feel shame感到羞耻
pugn = fight打斗
pur, purg = pure纯洁
put = think认为，思考
putr = rotten腐烂
quaint = know知道
quest, quir, quis, quer = seek, search寻求，询问
quiet, qui = still静
quit = free自由
radic = root根
rage = mad疯狂
range = rank排列，顺序
rap, rapt, rav = snatch捕，夺
ras, rad = scrape刮擦
rat = calculate计算
rect = straight, right正，直
rend = give给
rept = creep爬
rhythm = rhythm节奏
rid, ris = laugh笑
robor = strength力量(在如今的计算机领域经常听到”鲁棒”性，用来指软件或系统的健壮，就是它的音译而来)
rod, ros = bite咬
rog = ask要求，问
rot = wheel轮子，转
rub = red红（u-e,b-d,经过二次能假得来）
rud = rude原始，粗野
rupt = break断裂
rust, rur = country农村（rust是锈的意思，指农村不干净，到处锈迹斑斑）
sacr = holy神圣
sag = know知道
sal = leap跳
sal = salt盐
salv, save = save救助
san, sanit = healthy健康的
sanct = holy神圣
sanguin = blood血
sati, satis, satur = enough, full of food足够，饱足
scend, scens, scent = climb爬，攀
sci = know知道
scrib, script = write写
sect, seg = cut, divide切，割
secut, sequ = follow跟随
semin = seed种子
sen = old老
sens, sent = feel感觉
serr = saw锯子
sert = join, insert加入，插入
serv = serve, keep服务，保持
set = fix安置好
sever = earnest诚恳
sid = sit坐
sight = vision眼光
sign = mark记号，信号
simil, simul, sembl = alike, same相类似，一样
sinu = bend弯曲
sist = stand站立
soci = companion同伴，社会
sol = alone单独
sol = sun太阳
solv, solu, solut = loosen松开
som = body身体
somn = sleep睡眠
son = sound声音
soph = wise智慧，聪明
sort = kind种类
speci = look, kind外观，种类
spect, spic = look, see看
sper = hope希望
spers = scatter散开
spin = thorn刺
spir = breathe呼吸
splend = shine发光
spond, spons = promise承诺
st, sta, stat, stan, stant, stin = stand站，立
stall = place放
stell = star星星
stigma = mark标志，斑点
still = small drop小水滴
sting, stinct, stimul = prick刺，刺激
stitut, stit = set up, place建立，放
strain, strict, string = tighten拉紧
strat = spread out扩散，层次
struct = build建立
sult = leap跳
sum, summ = add up总，加
sume, sumpt = take拿，取
sur = sure肯定
surg = rise升起
tach = nail钉子
tact, tag, tig, ting = touch接触
tail = cut剪，割
tain, ten, tin, tinu = hold拿住
tard = slow慢
techn = skill, ability技术，能力
tect = cover盖上
tele = far远，电
temn, tempt = scorn蔑视
temper, tempor = time时间
tempt = try尝试
tend, tent, tens = stretch伸展
tenu = thin细，薄
termin = limit界限
terr = earth土地
terr = frighten恐，怕
test = test, witness测试，证据
text = weave编织
the(o) = god神
therm = heat热
thesis, thet = setting放置
tim = fear害怕
tir = draw拉
toler = endure容忍
tom, tomy = cut切割
tort = twist扭曲
touch = touch摸，碰
tour, torn = turn转
tox = poison毒
tract = draw拉，拖
treat = handle处理
trem = quiver颤抖
trench = cut切，割
tribut = give给予
trit = rub摩擦
trop = turn转
troph = nutrition营养
tru = true相信，真实
trud, trus = push推
turb = stir搅动
tut, tuit = protect保护
twine = twine编织
typ = type模式，形状
umbr = shadow影子
un, uni = one单一，一个
und = wave波动
up = up, over向上
urb = city城市
urin, ur = urine尿
us, util = use用
vac, vacu, van, void = empty空
vad, vas = go走
vag, vagr = wander漫游
vail, val = strong强壮
val, valu = value价值
vapor = steam蒸汽
vari, vary = change变化
veil = cover盖上
ven, vent = come来
venge = punish惩罚，报仇
vent = wind风
ver = true真实
verb = word词语
vers, vert = turn转
vest = clothes衣服
vestig = footprint, rack脚印，踪迹
vi, via, vey, voy = way道路
vibr = swing摇摆
vict, vinc = conquer, overcome征服，克服
vid, vis = see看
vid, vis = separate分开
vil = base卑劣
vir = man男人
viv, vit, vig = life生命
voc, vok = call, voice叫喊，声音
vol, volunt = wish, will意志，意愿
volv, volu, volt = roll, turn卷，转
vor = eat吃
vot = vow发誓
vulg = people人群
vuls, vult = pluck, tear收缩，撕开
ware = watch注视
zeal = ardor热心（Z只是为了代表闪电，故电又有激情、热流等含义）
zoo = animal动物
